# https://github.com/izumin5210/dotfiles/blob/aa17b272068491d24e7e52bd9fb58903c6947e4f/config/.config/lazygit/config.yml#L39-L49
git:
  branchLogCmd: "git log --graph --color=always --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' {{branchName}} --"
  allBranchesLogCmds:
    - git log --graph --color=always --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --all
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never --side-by-side
  mainBranches:
    - "main"
    - "master"
    - "develop"
  parseEmoji: true
gui:
  nerdFontsVersion: "3"
  border: "single"
  authorColors:
    "renovate[bot]": "#737994"
  theme:
    activeBorderColor:
      - "#ca9ee6"
      - bold
    inactiveBorderColor:
      - "#737994"
    optionsTextColor:
      - "#8caaee"
    selectedLineBgColor:
      - "#414559"
    cherryPickedCommitBgColor:
      - "#51576d"
    cherryPickedCommitFgColor:
      - "#ca9ee6"
    unstagedChangesColor:
      - "#e78284"
    defaultFgColor:
      - "#c6d0f5"
    searchingActiveBorderColor:
      - "#e5c890"
