[tools]
direnv = "latest"
neovim = "latest"
node = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@google/gemini-cli" = "latest"
uv = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python"]
