[tools]
bun = "latest"
delta = "latest"
direnv = "latest"
fzf = "latest"
gh = "latest"
ghq = "latest"
neovim = "latest"
node = "latest"
uv = "latest"
"npm:@openai/codex" = "latest"
claude = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python"]
